const fs = require('fs').promises;
const path = require('path');

// Upload a single file
exports.uploadFile = async (req, res) => {
  try {
    if (!req.file) {
      return res.status(400).json({
        status: 'error',
        message: 'No file uploaded'
      });
    }

    // Return the filename that was generated by multer
    res.status(200).json({
      status: 'success',
      data: {
        filename: req.file.filename,
        originalname: req.file.originalname,
        mimetype: req.file.mimetype,
        size: req.file.size
      }
    });
  } catch (error) {
    console.error('File upload error:', error);
    res.status(400).json({
      status: 'error',
      message: error.message
    });
  }
};

// Delete a file
exports.deleteFile = async (req, res) => {
  try {
    const filename = req.params.filename;
    const filepath = path.join(__dirname, '../uploads', filename);

    try {
      await fs.access(filepath); // Check if file exists
    } catch (err) {
      return res.status(404).json({
        status: 'error',
        message: 'File not found'
      });
    }

    await fs.unlink(filepath); // Delete the file

    res.status(200).json({
      status: 'success',
      message: 'File deleted successfully'
    });
  } catch (error) {
    console.error('File deletion error:', error);
    res.status(400).json({
      status: 'error',
      message: error.message
    });
  }
}; 